# Generated by Django 4.2.1 on 2023-05-09 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('seg', 'segunda-feira'), ('ter', 'terca-feira'), ('qua', 'quarta-feira'), ('qui', 'quinta-feira'), ('sex', 'sexta-feira')], max_length=13, unique=True)),
                ('minimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('maximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Comissao',
                'verbose_name_plural': 'Comissoes',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=50, null=True)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('comissao', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(max_length=10, unique=True)),
                ('data', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.cliente')),
                ('produtos', models.ManyToManyField(through='django_api.ProdutoVendido', to='django_api.produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='produtovendido',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.venda'),
        ),
    ]
